version: '3.1'
services:
  webapp:
    build: .
    container_name: webapp01
    ports:
      - "8000:5000"
    environment:
      - FLASK_APP=my_app.py
    command: flask run --host 0.0.0.0
    volumes:
      - myapp:/app
    links:
      - redis
      - mongo
      - celery
    depends_on:
      - redis
      - mongo
      - celery
  celery:
    build: .
    container_name: celery01
    command: celery -A app.routes.celery worker --loglevel=info
    volumes:
      - myapp:/app
  redis:
    image: redis:latest
    container_name: redis01
    ports:
      - "6379:6379"
    depends_on:
      - celery
  mongo:
    image: mongo:latest
    container_name: mongo01
    ports:
      - "27017:27017"
volumes:
  myapp: